spring.application.name=bai1
server.port=8761

# Không ??ng ký chính nó
eureka.client.register-with-eureka=false

# Không l?y registry t? chính nó
eureka.client.fetch-registry=false

# T?t self-preservation
eureka.server.enable-self-preservation=false